### ISSUE TITLE
data-gradients with yolo-nas

### ISSUE THREAD

**Issue by oussaifi-majdi** [Deci-AI/data-gradients#190]
### 💡 Your Question

how i can use data-gradients in yolo-nas to show me a repport of accurancy,recall ,precision..etc

**Comment by Louis-Dupont** [comment]
Hi @oussaifi-majdi ,
DataGradients currently primarily focus on Data Exploration, and not on model result analysis.

Its core functionality addresses situations where users possess a dataset and wish to understand its structure, primarily to determine its suitability for training their models. 
One of its key use cases is assisting users in selecting the right dataset for a specific task, ensuring that the chosen dataset meets certain criteria. 

Your question is basically only related to SuperGradients.
First, you should already have access to recall@0.50 and precision@0.50 during training (as well as Map and F1). They are printed, and if you use wandb it will also be uploaded to it. In any case, there are also local logs files in the experiment directory, that will indicate the scores for each epoch.
Concerning accuracy, it is not included because it's not really meaningful in the context of Object detection, unlike the above-mentioned metrics.
Does that answer your question ?
